format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

[directory]
style = "blue"
truncation_length = 3
truncation_symbol = '.../'
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"

[git_branch]
style = "bright-black"

[git_status]
style = "cyan"
