# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[line_break]
disabled = false

[character]
error_symbol = "[➜](bold red) "
success_symbol = "[➜](bold green)"

[directory]
truncation_length = 5
home_symbol = " "
format = "[$path](bold italic yellow) "

[hostname]
ssh_only = false
disabled = false
style = "underline italic purple"

[package]
disabled = true

[username]
show_always = true
style_user = "bold red"
format =  "[$user]($style)[ in ](white)"
