import = [
  "~/.config/alacritty/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"
